import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// Route de synchronisation de schéma EXÉCUTÉE PAR LE RUNTIME (qui joint la base,
// contrairement au build). Strictement additif : CREATE TABLE / ADD COLUMN /
// CREATE INDEX en « IF NOT EXISTS ». Aucune suppression, aucune perte de données.
// Couvre le schéma de la version récente (modèle User, colonnes carte/calendar…).
// À usage ponctuel : protégée par token, à retirer une fois la base à jour.
export const dynamic = 'force-dynamic';

const TOKEN = 'sync-crm-2026';

const STATEMENTS: string[] = [
  "CREATE TABLE IF NOT EXISTS \"Brand\" (\"id\" TEXT NOT NULL, CONSTRAINT \"Brand_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"Store\" (\"id\" TEXT NOT NULL, CONSTRAINT \"Store_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"Collaborator\" (\"id\" TEXT NOT NULL, CONSTRAINT \"Collaborator_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"User\" (\"id\" TEXT NOT NULL, CONSTRAINT \"User_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"Pipeline\" (\"id\" TEXT NOT NULL, CONSTRAINT \"Pipeline_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"PipelineColumn\" (\"id\" TEXT NOT NULL, CONSTRAINT \"PipelineColumn_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"Deal\" (\"id\" TEXT NOT NULL, CONSTRAINT \"Deal_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"JobOffer\" (\"id\" TEXT NOT NULL, CONSTRAINT \"JobOffer_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"ImportBatch\" (\"id\" TEXT NOT NULL, CONSTRAINT \"ImportBatch_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"ImportRow\" (\"id\" TEXT NOT NULL, CONSTRAINT \"ImportRow_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"Action\" (\"id\" TEXT NOT NULL, CONSTRAINT \"Action_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"Note\" (\"id\" TEXT NOT NULL, CONSTRAINT \"Note_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"EmailTemplate\" (\"id\" TEXT NOT NULL, CONSTRAINT \"EmailTemplate_pkey\" PRIMARY KEY (\"id\"));",
  "CREATE TABLE IF NOT EXISTS \"EmailLog\" (\"id\" TEXT NOT NULL, CONSTRAINT \"EmailLog_pkey\" PRIMARY KEY (\"id\"));",
  "ALTER TABLE \"Brand\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"Brand\" ADD COLUMN IF NOT EXISTS \"name\" TEXT;",
  "ALTER TABLE \"Brand\" ADD COLUMN IF NOT EXISTS \"color\" TEXT NOT NULL DEFAULT '#6366f1';",
  "ALTER TABLE \"Brand\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Brand\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"brandId\" TEXT;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"name\" TEXT;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"normalizedName\" TEXT;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"city\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"postalCode\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"department\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"address\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"phone\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"email\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"siret\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"externalId\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"deduplicationKey\" TEXT;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"latitude\" DOUBLE PRECISION;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"longitude\" DOUBLE PRECISION;",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"geocodedAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"geocodeQuery\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"Collaborator\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"Collaborator\" ADD COLUMN IF NOT EXISTS \"name\" TEXT;",
  "ALTER TABLE \"Collaborator\" ADD COLUMN IF NOT EXISTS \"email\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Collaborator\" ADD COLUMN IF NOT EXISTS \"color\" TEXT NOT NULL DEFAULT '#6366f1';",
  "ALTER TABLE \"Collaborator\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Collaborator\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"User\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"User\" ADD COLUMN IF NOT EXISTS \"name\" TEXT;",
  "ALTER TABLE \"User\" ADD COLUMN IF NOT EXISTS \"color\" TEXT NOT NULL DEFAULT '#6366f1';",
  "ALTER TABLE \"User\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"User\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"Pipeline\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"Pipeline\" ADD COLUMN IF NOT EXISTS \"name\" TEXT;",
  "ALTER TABLE \"Pipeline\" ADD COLUMN IF NOT EXISTS \"position\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"Pipeline\" ADD COLUMN IF NOT EXISTS \"color\" TEXT NOT NULL DEFAULT '#6366f1';",
  "ALTER TABLE \"Pipeline\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Pipeline\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"pipelineId\" TEXT;",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"title\" TEXT;",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"position\" INTEGER;",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"color\" TEXT NOT NULL DEFAULT '#6366f1';",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"isDefault\" BOOLEAN NOT NULL DEFAULT false;",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"PipelineColumn\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"pipelineId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"storeId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"columnId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"previousColumnId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"priority\" TEXT NOT NULL DEFAULT 'normale';",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"position\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"isNewFromLastImport\" BOOLEAN NOT NULL DEFAULT false;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"hasNewOfferFromLastImport\" BOOLEAN NOT NULL DEFAULT false;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"isPresentInLastImport\" BOOLEAN NOT NULL DEFAULT true;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"movedToCallAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"lastImportAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"directeur\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"contactCalling\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"dealEmail\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"contactCivilite\" TEXT NOT NULL DEFAULT 'Monsieur';",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"contactLastName\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"dealValue\" DOUBLE PRECISION;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"demoDate\" TIMESTAMP(3);",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"candidateCallDate\" TIMESTAMP(3);",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"googleEventId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"googleMeetUrl\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"supabaseOrganizationId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"collaboratorId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"assignedUserId\" TEXT;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"storeId\" TEXT;",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"importBatchId\" TEXT;",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"externalOfferId\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"title\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"jobTitle\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"contractType\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"salary\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"source\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"url\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"publishedAt\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"fingerprint\" TEXT;",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"firstSeenAt\" TIMESTAMP(3);",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"lastSeenAt\" TIMESTAMP(3);",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"JobOffer\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"fileName\" TEXT;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"importedAt\" TIMESTAMP(3);",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"totalRows\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"createdDeals\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"updatedDeals\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"newOffers\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"movedToCall\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"errorCount\" INTEGER NOT NULL DEFAULT 0;",
  "ALTER TABLE \"ImportBatch\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"importBatchId\" TEXT;",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"rowNumber\" INTEGER;",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"rawData\" JSONB;",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"status\" TEXT NOT NULL DEFAULT 'ok';",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"errorMessage\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"storeId\" TEXT;",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"ImportRow\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"title\" TEXT;",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"type\" TEXT NOT NULL DEFAULT 'Appeler';",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"dueDate\" TIMESTAMPTZ;",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"dueTime\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"status\" TEXT NOT NULL DEFAULT 'todo';",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"priority\" TEXT NOT NULL DEFAULT 'normale';",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"note\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"completedAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"assignedUserId\" TEXT;",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Action\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"Note\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"Note\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"Note\" ADD COLUMN IF NOT EXISTS \"content\" TEXT;",
  "ALTER TABLE \"Note\" ADD COLUMN IF NOT EXISTS \"authorId\" TEXT;",
  "ALTER TABLE \"Note\" ADD COLUMN IF NOT EXISTS \"authorName\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Note\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Note\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"EmailTemplate\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"EmailTemplate\" ADD COLUMN IF NOT EXISTS \"name\" TEXT;",
  "ALTER TABLE \"EmailTemplate\" ADD COLUMN IF NOT EXISTS \"subject\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"EmailTemplate\" ADD COLUMN IF NOT EXISTS \"body\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"EmailTemplate\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"EmailTemplate\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"templateId\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"to\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"cc\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"subject\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"body\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"status\" TEXT NOT NULL DEFAULT 'sent';",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"resendId\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"openedAt\" TIMESTAMP(3);",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"sentAt\" TIMESTAMP(3);",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  // Suivi des RÉPONSES (Resend Inbound) : sens de l'email, expéditeur et
  // en-têtes de threading. Défaut 'outbound' = tout l'historique existant.
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"direction\" TEXT NOT NULL DEFAULT 'outbound';",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"fromAddress\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"messageId\" TEXT;",
  "ALTER TABLE \"EmailLog\" ADD COLUMN IF NOT EXISTS \"inReplyTo\" TEXT;",
  "CREATE INDEX IF NOT EXISTS \"EmailLog_dealId_sentAt_idx\" ON \"EmailLog\"(\"dealId\", \"sentAt\");",
  "CREATE INDEX IF NOT EXISTS \"EmailLog_resendId_idx\" ON \"EmailLog\"(\"resendId\");",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"lastEmailReplyAt\" TIMESTAMP(3);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"User_name_key\" ON \"User\"(\"name\");",
  // Authentification : identifiants de connexion par utilisateur.
  "ALTER TABLE \"User\" ADD COLUMN IF NOT EXISTS \"email\" TEXT;",
  "ALTER TABLE \"User\" ADD COLUMN IF NOT EXISTS \"passwordHash\" TEXT;",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"User_email_key\" ON \"User\"(\"email\");",
  "CREATE TABLE IF NOT EXISTS \"CandidateCall\" (\"id\" TEXT NOT NULL, CONSTRAINT \"CandidateCall_pkey\" PRIMARY KEY (\"id\"));",
  "ALTER TABLE \"CandidateCall\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"CandidateCall\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"CandidateCall\" ADD COLUMN IF NOT EXISTS \"candidateId\" TEXT;",
  "ALTER TABLE \"CandidateCall\" ADD COLUMN IF NOT EXISTS \"calledAt\" TIMESTAMP(3);",
  "ALTER TABLE \"CandidateCall\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "ALTER TABLE \"CandidateCall\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"CandidateCall_dealId_candidateId_key\" ON \"CandidateCall\"(\"dealId\",\"candidateId\");",
  "CREATE TABLE IF NOT EXISTS \"AppSetting\" (\"key\" TEXT NOT NULL, CONSTRAINT \"AppSetting_pkey\" PRIMARY KEY (\"key\"));",
  "ALTER TABLE \"AppSetting\" ADD COLUMN IF NOT EXISTS \"key\" TEXT;",
  "ALTER TABLE \"AppSetting\" ADD COLUMN IF NOT EXISTS \"value\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"AppSetting\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"supabaseOrgManual\" BOOLEAN NOT NULL DEFAULT false;",
  "CREATE TABLE IF NOT EXISTS \"DealOrganization\" (\"id\" TEXT NOT NULL, CONSTRAINT \"DealOrganization_pkey\" PRIMARY KEY (\"id\"));",
  "ALTER TABLE \"DealOrganization\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"DealOrganization\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"DealOrganization\" ADD COLUMN IF NOT EXISTS \"organizationId\" TEXT;",
  "ALTER TABLE \"DealOrganization\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"DealOrganization_dealId_organizationId_key\" ON \"DealOrganization\"(\"dealId\",\"organizationId\");",
  // Regroupement d'affaires (deal parent / sous-deals).
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"parentDealId\" TEXT;",
  "CREATE INDEX IF NOT EXISTS \"Deal_parentDealId_idx\" ON \"Deal\"(\"parentDealId\");",
  // Notifications d'offres produit (Supabase) rattachées aux affaires.
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"offersSyncedAt\" TIMESTAMP(3);",
  "CREATE TABLE IF NOT EXISTS \"OfferNotification\" (\"id\" TEXT NOT NULL, CONSTRAINT \"OfferNotification_pkey\" PRIMARY KEY (\"id\"));",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"organizationId\" TEXT;",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"offerId\" TEXT;",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"offerTitle\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"offerCreatedAt\" TIMESTAMP(3);",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"isRead\" BOOLEAN NOT NULL DEFAULT false;",
  "ALTER TABLE \"OfferNotification\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3);",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"OfferNotification_dealId_offerId_key\" ON \"OfferNotification\"(\"dealId\",\"offerId\");",
  "CREATE INDEX IF NOT EXISTS \"OfferNotification_dealId_idx\" ON \"OfferNotification\"(\"dealId\");",
  // Téléphone du contact (saisi sur la fiche affaire) + journal des appels
  // alimenté par les clics sur « Afficher le numéro ».
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"contactPhone\" TEXT NOT NULL DEFAULT '';",
  "CREATE TABLE IF NOT EXISTS \"CallLog\" (\"id\" TEXT NOT NULL, CONSTRAINT \"CallLog_pkey\" PRIMARY KEY (\"id\"));",
  "ALTER TABLE \"CallLog\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"CallLog\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"CallLog\" ADD COLUMN IF NOT EXISTS \"userId\" TEXT;",
  "ALTER TABLE \"CallLog\" ADD COLUMN IF NOT EXISTS \"userName\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"CallLog\" ADD COLUMN IF NOT EXISTS \"phone\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"CallLog\" ADD COLUMN IF NOT EXISTS \"calledAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  // Décisionnaire joint ou non (réponse à la pop-up affichée après l'appel).
  // Nullable : les appels enregistrés avant cette question restent « inconnu ».
  "ALTER TABLE \"CallLog\" ADD COLUMN IF NOT EXISTS \"connected\" BOOLEAN;",
  "CREATE INDEX IF NOT EXISTS \"CallLog_calledAt_idx\" ON \"CallLog\"(\"calledAt\");",
  "CREATE INDEX IF NOT EXISTS \"CallLog_userId_calledAt_idx\" ON \"CallLog\"(\"userId\",\"calledAt\");",
  "CREATE INDEX IF NOT EXISTS \"CallLog_dealId_idx\" ON \"CallLog\"(\"dealId\");",
  // Journal des déplacements d'affaires (changement d'étape et/ou de pipeline).
  "CREATE TABLE IF NOT EXISTS \"DealMove\" (\"id\" TEXT NOT NULL, CONSTRAINT \"DealMove_pkey\" PRIMARY KEY (\"id\"));",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"fromColumnId\" TEXT;",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"fromColumnTitle\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"fromPipelineId\" TEXT;",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"fromPipelineName\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"toColumnId\" TEXT;",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"toColumnTitle\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"toPipelineId\" TEXT;",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"toPipelineName\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"userId\" TEXT;",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"userName\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"source\" TEXT NOT NULL DEFAULT 'pipeline';",
  "ALTER TABLE \"DealMove\" ADD COLUMN IF NOT EXISTS \"movedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "CREATE INDEX IF NOT EXISTS \"DealMove_dealId_movedAt_idx\" ON \"DealMove\"(\"dealId\",\"movedAt\");",
  "CREATE INDEX IF NOT EXISTS \"DealMove_movedAt_idx\" ON \"DealMove\"(\"movedAt\");",
  "CREATE INDEX IF NOT EXISTS \"DealMove_userId_movedAt_idx\" ON \"DealMove\"(\"userId\",\"movedAt\");",
  // Booking de démo : miroir de la date du dernier booking sur l'affaire…
  "ALTER TABLE \"Deal\" ADD COLUMN IF NOT EXISTS \"demoBookedAt\" TIMESTAMP(3);",
  // …et historique complet (une ligne par passage dans « DEMO PREVUE » du
  // pipeline Closing, rebookings compris) avec sa case NO SHOW.
  "CREATE TABLE IF NOT EXISTS \"DemoBooking\" (\"id\" TEXT NOT NULL, CONSTRAINT \"DemoBooking_pkey\" PRIMARY KEY (\"id\"));",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"id\" TEXT;",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"dealId\" TEXT;",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"userId\" TEXT;",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"userName\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"bookedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"demoDate\" TIMESTAMP(3);",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"noShow\" BOOLEAN NOT NULL DEFAULT false;",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"DemoBooking\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "CREATE INDEX IF NOT EXISTS \"DemoBooking_dealId_bookedAt_idx\" ON \"DemoBooking\"(\"dealId\",\"bookedAt\");",
  "CREATE INDEX IF NOT EXISTS \"DemoBooking_bookedAt_idx\" ON \"DemoBooking\"(\"bookedAt\");",
  "CREATE INDEX IF NOT EXISTS \"DemoBooking_userId_bookedAt_idx\" ON \"DemoBooking\"(\"userId\",\"bookedAt\");",
  // Recherche automatique des numéros de téléphone des magasins : trace de la
  // dernière recherche (source, statut, date) et candidats en attente de
  // validation. Le numéro lui-même vit dans la colonne "phone" déjà existante.
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"phoneSource\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"phoneLookupStatus\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"phoneLookupAt\" TIMESTAMP(3);",
  "ALTER TABLE \"Store\" ADD COLUMN IF NOT EXISTS \"phoneCandidates\" JSONB;",
  "CREATE INDEX IF NOT EXISTS \"Store_phoneLookupStatus_idx\" ON \"Store\"(\"phoneLookupStatus\");",
  // Attribution des liens de paiement « classiques » aux cases du plan tarifaire
  // (Paramètres › Liens de paiement). Une ligne par case occupée ; le plan
  // lui-même vit dans src/lib/paymentLinkSlots.ts.
  "CREATE TABLE IF NOT EXISTS \"PaymentLinkSlot\" (\"slotKey\" TEXT NOT NULL, CONSTRAINT \"PaymentLinkSlot_pkey\" PRIMARY KEY (\"slotKey\"));",
  "ALTER TABLE \"PaymentLinkSlot\" ADD COLUMN IF NOT EXISTS \"slotKey\" TEXT;",
  "ALTER TABLE \"PaymentLinkSlot\" ADD COLUMN IF NOT EXISTS \"stripeLinkId\" TEXT NOT NULL DEFAULT '';",
  "ALTER TABLE \"PaymentLinkSlot\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "ALTER TABLE \"PaymentLinkSlot\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;",
  "CREATE INDEX IF NOT EXISTS \"PaymentLinkSlot_stripeLinkId_idx\" ON \"PaymentLinkSlot\"(\"stripeLinkId\");",
  // La table PaymentLinkConfig d'une version précédente n'est plus utilisée.
  // Elle n'est pas supprimée ici (cette route reste strictement additive) ; elle
  // peut être retirée à la main si elle existe.
];

export async function GET(req: NextRequest) {
  if (req.nextUrl.searchParams.get('token') !== TOKEN) {
    return NextResponse.json({ error: 'Token invalide' }, { status: 401 });
  }
  const applied: string[] = [];
  const errors: { sql: string; error: string }[] = [];
  for (const sql of STATEMENTS) {
    try {
      await prisma.$executeRawUnsafe(sql);
      applied.push(sql);
    } catch (e) {
      errors.push({ sql, error: e instanceof Error ? e.message : String(e) });
    }
  }
  return NextResponse.json({
    ok: errors.length === 0,
    appliedCount: applied.length,
    errorCount: errors.length,
    errors,
  });
}
